apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-despacho
  namespace: proyecto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-despacho
  template:
    metadata:
      labels:
        app: front-despacho
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: front-despacho
        image: 046533024277.dkr.ecr.us-east-1.amazonaws.com/devops/front-despacho:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
