version: "3.8"

services:
  proyecto-db:
    image: ${ECR_REPO_URL_DB}:v1
    container_name: proyecto-db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
  dbdata:
    driver: local
