version: "3.8"

services:
  proyecto-db:
    image: ${ECR_REPO_URL_DB}:v1
    container_name: proyecto-db
    restart: always          # <-- se levanta solo al encender la instancia
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_USERNAME}

volumes:
  dbdata:
    driver: local
