name: CI/CD Backend Ventas
on:
  push:
    branches: [ "deploy" ]
    paths:
      - "back-Ventas_SpringBoot/Springboot-API-REST/**"

jobs:
  build-push-deploy-backend-ventas:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR (runner)
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build imagen Backend Ventas y push a ECR
      run: |
        cd back-Ventas_SpringBoot/Springboot-API-REST
        docker build -t back-ventas .
        docker tag back-ventas:latest ${{ secrets.ECR_REPO_URL_BACKEND_VENTAS }}:v1
        docker push ${{ secrets.ECR_REPO_URL_BACKEND_VENTAS }}:v1

    - name: Desplegar Backend Ventas vía SSM
      continue-on-error: true
      run: |
        aws ssm send-command \
          --instance-ids ${{ secrets.EC2_BACKEND_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --comment "Actualizar back-ventas desde ECR" \
          --parameters '{"commands":[
            "set -e",
            "curl -L -o /home/ec2-user/docker-compose.yml https://raw.githubusercontent.com/funnyname05/DevOps-Proyecto/refs/heads/main/Backend/docker-compose.yml",
            "source /home/ec2-user/.env",
            "aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY",
            "cd /home/ec2-user",
            "docker compose pull",
            "docker compose up -d --force-recreate --remove-orphans"
          ]}' \
          --output text

    - name: Instalar kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/kubectl

    - name: Actualizar imagen en EKS
      run: |
        aws eks update-kubeconfig \
          --region ${{ secrets.AWS_REGION }} \
          --name ${{ secrets.EKS_CLUSTER_NAME }}
        kubectl set image deployment/back-ventas \
          back-ventas=${{ secrets.ECR_REPO_URL_BACKEND_VENTAS }}:v1 \
          -n proyecto
        kubectl rollout status deployment/back-ventas -n proyecto
